class StatusCode:
    OK = "OK"
    CREATED = "CREATED"
    NOT_FOUND = "NOT_FOUND"
    INVALID_FIELD = "INVALID_FIELD"
    INVALID_INPUT = "INVALID_INPUT"
    DB_ERROR = "DB_ERROR"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
    DUPLICATE_OR_INVALID = "DUPLICATE_OR_INVALID"
